var operandA = 10;
var operandB = 5;
var truth = true;
var falsy = false;
console.log("Arithmetic Operations");
console.log("Addition: ", operandA + operandB);
console.log("Subtraction: ", operandA - operandB);
console.log("Multiplication: ", operandA * operandB);
console.log("Division: ", operandA / operandB);
console.log("Comparison Operations");
console.log("Equal: ", operandA == operandB);
console.log("Not Equal: ", operandA != operandB);
console.log("Greater Than: ", operandA > operandB);
console.log("Less Than: ", operandA < operandB);
console.log("Greater Than or Equal: ", operandA >= operandB);
console.log("Less Than or Equal: ", operandA <= operandB);
console.log("Logical Operations");
console.log("AND: ", truth && falsy);
console.log("OR: ", truth || falsy);
console.log("NOT: ", !truth);
